name: Node.js CI

on: 
  push:
    branches: 
      - main
      - master

  #schedule:
    #- cron: "0 2 * * 1-5"


# will be triggered jobs
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    
    # main command will be executed
    steps:
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm 
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node- 
          ${{ runner.OS }}-
          
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: yarn test --watchAll=false
      env:
        CI: true
