name: Node.js CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # setup debug
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Setup Nodejs Env
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --watchAll=false

      - name: Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker image
        uses: actions/cache@v2
        with:
          path: nginx.tar
          key: ${{ runner.os }}-image-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-image-

      - name: Pull docker base image and save
        run: "docker pull nginx && docker save nginx > nginx.tar"

      - name: Build docker image
        run: "docker build -t yisen614/react-project:v1 ."

      - name: Push docker image
        run: "docker push yisen614/react-project:v1"
