name: Node.js CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs Env
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Show files before
        run: "ls -la"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Show files after dependencies installed
        run: "ls -la"

      - name: Test
        run: yarn test --watchAll=false

      - name: Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: Show files after build artifacts
        run: "ls -la"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yisen614/react-project:v1
          build-args: |
            arg1=value1
            arg2=value2
